---
- block:
  - name: install pacemaker and pcs
    yum:
        name: '{{ item }}'
        state: present
    with_items:
        '{{ clusterpkgs }}'

  - name: start pcsd
    service:
        name: pcsd
        state: started

  - name: enable pcsd
    systemd:
        name: pcsd
        enabled: yes

  - name: hacluster User
    user:
        name: '{{ cluser }}'
        groups: haclient
        append: yes
        shell: /bin/bash
        password: "{{  clpass | password_hash('sha512') }}"

  - name: enable services
    systemd:
        name: '{{ item }}'
        enabled: yes
    with_items:
        '{{ clservices }}'


  - name: update cluster auth ansclient1 ansclient2
    command: sudo pcs cluster auth webnode01 webnode02 \
             -u '{{ cluser }}'  -p '{{ clpass }}'
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: setup cluster
    command: sudo pcs cluster setup --name webcluster \
             webnode01 webnode02 --force
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: start cluster
    command: sudo pcs cluster start --all
    run_once: true
    delegate_to: '{{ node1 }}'

  - name: disable stonith
    command: sudo pcs property set stonith-enabled='{{IS_STONITH_ON}}'
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: ignore quorum
    command: sudo pcs property set no-quorum-policy=ignore
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: create VIP resource
    command: sudo pcs resource create Cluster_VIP \
             ocf:heartbeat:IPaddr2 \
             ip=127.0.0.2 cidr_netmask=24 op monitor interval=20s
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: create Apache resource
    command: sudo pcs resource create WebServer \
             ocf:heartbeat:apache \
             configfile=/etc/httpd/conf/httpd.conf \
             statusurl="http://127.0.0.1/server-status" \
             op monitor interval=20s
    run_once: true
    delegate_to: '{{ node1 }}'
  - name: configure collocation constraints
    command: sudo pcs constraint colocation add WebServer \
             Cluster_VIP INFINITY
    run_once: true
    delegate_to: '{{ node1 }}'

  rescue:
      - name: Rescue block (perform recovery)
        debug:
            msg: "Something went wrong..Please run the rollback.sh script"
