---
- block:
  - name: install pacemaker and pcs
    yum:
        name: '{{ item }}'
        state: present
    with_items:
        '{{ clusterpkgs }}'

  - name: start pcsd
    service:
        name: pcsd
        state: started

  - name: enable pcsd
    systemd:
        name: pcsd
        enabled: yes

  - name: hacluster User
    user:
        name: '{{ cluser }}'
        groups: haclient
        append: yes
        shell: /bin/bash
        password: "{{  clpass | password_hash('sha512') }}"

  - name: enable services
    systemd:
        name: '{{ item }}'
        enabled: yes
    with_items:
        '{{ clservices }}'

  rescue:
      - name: Rescue block (perform recovery)
        debug:
            msg: "Something went wrong..Please run the rollback.sh script"
